version: "3.1"
services:

  app:
    image: lampikoski/git-pull:latest
    environment:
      GIT_COMMIT: master
      GIT_HOST: ${GIT_HOST:-github.com}
      GIT_REPO: ${GIT_REPO:-ssh://git@github.com:myrepo/admin.git}
      INTERVAL: 60
    volumes:
    - /tmp:/git
    secrets:
    - git-deploy_sshkey
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s

secrets:
  git-deploy_sshkey:
    external: true
